"Filed out from Dolphin Smallalk"!

SQLite3LogWarning subclass: #SQLite3LogWarningAutoIndex
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
SQLite3LogWarningAutoIndex guid: (GUID fromString: '{34bd597f-aeb6-4163-8133-087c4191c81f}')!
SQLite3LogWarningAutoIndex comment: 'SQLite3LogWarningAutoIndex class	instanceVariableNames: '''''!
!SQLite3LogWarningAutoIndex categoriesForClass!SQLite3-Core-Errors-Extended! !
!SQLite3LogWarningAutoIndex class methodsFor!

nativeErrorCode	^ SQLITE_WARNING_AUTOINDEX! !
!SQLite3LogWarningAutoIndex class categoriesForMethods!
nativeErrorCode!private / accessing!public! !
!

