"Filed out from Dolphin Smallalk"!

SQLite3NativeError subclass: #SQLite3Abort
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
SQLite3Abort guid: (GUID fromString: '{dc6f96b0-c2cd-49a9-9d10-12f5765859d7}')!
SQLite3Abort comment: 'SQLite3Abort class	instanceVariableNames: '''''!
!SQLite3Abort categoriesForClass!SQLite3-Core-Errors! !
!SQLite3Abort class methodsFor!

nativeErrorCode	 		^ SQLITE_ABORT! !
!SQLite3Abort class categoriesForMethods!
nativeErrorCode!private / accessing!public! !
!

