"Filed out from Dolphin Smallalk"!

SQLite3IOError subclass: #SQLite3IOErrorConvertPath
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
SQLite3IOErrorConvertPath guid: (GUID fromString: '{ff481796-20b3-4f71-9bc0-c9c83087a2b0}')!
SQLite3IOErrorConvertPath comment: 'SQLite3IOErrorConvertPath class	instanceVariableNames: '''''!
!SQLite3IOErrorConvertPath categoriesForClass!SQLite3-Core-Errors-Extended! !
!SQLite3IOErrorConvertPath class methodsFor!

nativeErrorCode		^ SQLITE_IOERR_CONVPATH! !
!SQLite3IOErrorConvertPath class categoriesForMethods!
nativeErrorCode!private / accessing!public! !
!

