"Filed out from Dolphin Smallalk"!

SQLite3Busy subclass: #SQLite3BusyRecovery
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
SQLite3BusyRecovery guid: (GUID fromString: '{fd1dce96-42e3-46d1-a6c6-e5bce574b01b}')!
SQLite3BusyRecovery comment: 'SQLite3BusyRecovery class	instanceVariableNames: '''''!
!SQLite3BusyRecovery categoriesForClass!SQLite3-Core-Errors-Extended! !
!SQLite3BusyRecovery class methodsFor!

nativeErrorCode	^ SQLITE_BUSY_RECOVERY! !
!SQLite3BusyRecovery class categoriesForMethods!
nativeErrorCode!private / accessing!public! !
!

