"Filed out from Dolphin Smallalk"!

SQLite3Abort subclass: #SQLite3AbortRollback
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
SQLite3AbortRollback guid: (GUID fromString: '{e48e2637-0b5e-44b3-bd33-45f2b69bf63d}')!
SQLite3AbortRollback comment: 'SQLite3AbortRollback class	instanceVariableNames: '''''!
!SQLite3AbortRollback categoriesForClass!SQLite3-Core-Errors-Extended! !
!SQLite3AbortRollback class methodsFor!

nativeErrorCode	^ SQLITE_ABORT_ROLLBACK! !
!SQLite3AbortRollback class categoriesForMethods!
nativeErrorCode!private / accessing!public! !
!

