"Filed out from Dolphin Smallalk"!

SQLite3IOErrorSharedMemoryError subclass: #SQLite3IOErrorSharedMemoryOpen
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
SQLite3IOErrorSharedMemoryOpen guid: (GUID fromString: '{25572be5-ebfe-4fa0-967f-3aebce45c81a}')!
SQLite3IOErrorSharedMemoryOpen comment: 'SQLite3IOErrorSharedMemoryOpen class	instanceVariableNames: '''''!
!SQLite3IOErrorSharedMemoryOpen categoriesForClass!SQLite3-Core-Errors-Extended! !
!SQLite3IOErrorSharedMemoryOpen class methodsFor!

nativeErrorCode 	^ SQLITE_IOERR_SHMOPEN! !
!SQLite3IOErrorSharedMemoryOpen class categoriesForMethods!
nativeErrorCode!private / accessing!public! !
!

