"Filed out from Dolphin Smallalk"!

SQLite3NativeError subclass: #SQLite3IOError
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
SQLite3IOError guid: (GUID fromString: '{1ba396ec-4803-42f3-9f71-a805639bf511}')!
SQLite3IOError comment: 'SQLite3IOError class	instanceVariableNames: '''''!
!SQLite3IOError categoriesForClass!SQLite3-Core-Errors! !
!SQLite3IOError class methodsFor!

nativeErrorCode	^ SQLITE_IOERR! !
!SQLite3IOError class categoriesForMethods!
nativeErrorCode!private / accessing!public! !
!

