"Filed out from Dolphin Smallalk"!

SQLite3Result subclass: #SQLite3OKResult
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
SQLite3OKResult guid: (GUID fromString: '{211446fc-d6d9-4df9-97ff-0b11767ef9cf}')!
SQLite3OKResult comment: 'SQLite3OKResult class	instanceVariableNames: '''''!
!SQLite3OKResult categoriesForClass!SQLite3-Core-Results! !
!SQLite3OKResult class methodsFor!

nativeResultCode	^ SQLITE_OK! !
!SQLite3OKResult class categoriesForMethods!
nativeResultCode!private / accessing!public! !
!

