"Filed out from Dolphin Smallalk"!

SQLite3IOErrorDelete subclass: #SQLite3IOErrorDeleteNoEntry
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
SQLite3IOErrorDeleteNoEntry guid: (GUID fromString: '{bf8e31c2-463d-4f28-9874-4d2fa48433da}')!
SQLite3IOErrorDeleteNoEntry comment: 'SQLite3IOErrorDeleteNoEntry class	instanceVariableNames: '''''!
!SQLite3IOErrorDeleteNoEntry categoriesForClass!SQLite3-Core-Errors-Extended! !
!SQLite3IOErrorDeleteNoEntry class methodsFor!

nativeErrorCode	^ SQLITE_IOERR_DELETE_NOENT! !
!SQLite3IOErrorDeleteNoEntry class categoriesForMethods!
nativeErrorCode!private / accessing!public! !
!

