"Filed out from Dolphin Smallalk"!

SQLite3NativeError subclass: #SQLite3LogNotice
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
SQLite3LogNotice guid: (GUID fromString: '{971aeefd-130b-47b7-828a-3bb6f33532df}')!
SQLite3LogNotice comment: 'SQLite3LogNotice class	instanceVariableNames: '''''!
!SQLite3LogNotice categoriesForClass!SQLite3-Core-Errors! !
!SQLite3LogNotice class methodsFor!

nativeErrorCode	^ SQLITE_NOTICE! !
!SQLite3LogNotice class categoriesForMethods!
nativeErrorCode!private / accessing!public! !
!

