"Filed out from Dolphin Smallalk"!

SQLite3ReadOnly subclass: #SQLite3ReadOnlyRecovery
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
SQLite3ReadOnlyRecovery guid: (GUID fromString: '{de69e319-3169-4640-b483-dd3ddccf6b71}')!
SQLite3ReadOnlyRecovery comment: 'SQLite3ReadOnlyRecovery class	instanceVariableNames: '''''!
!SQLite3ReadOnlyRecovery categoriesForClass!SQLite3-Core-Errors-Extended! !
!SQLite3ReadOnlyRecovery class methodsFor!

nativeErrorCode	^ SQLITE_READONLY_RECOVERY! !
!SQLite3ReadOnlyRecovery class categoriesForMethods!
nativeErrorCode!private / accessing!public! !
!

