"Filed out from Dolphin Smallalk"!

SQLite3IOError subclass: #SQLite3IOErrorCheckReservedLock
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
SQLite3IOErrorCheckReservedLock guid: (GUID fromString: '{057c0397-5394-4db1-b4a8-53e3ab4350ef}')!
SQLite3IOErrorCheckReservedLock comment: 'SQLite3IOErrorCheckReservedLock class	instanceVariableNames: '''''!
!SQLite3IOErrorCheckReservedLock categoriesForClass!SQLite3-Core-Errors-Extended! !
!SQLite3IOErrorCheckReservedLock class methodsFor!

nativeErrorCode 	^ SQLITE_IOERR_CHECKRESERVEDLOCK! !
!SQLite3IOErrorCheckReservedLock class categoriesForMethods!
nativeErrorCode!private / accessing!public! !
!

