"Filed out from Dolphin Smallalk"!

SQLite3IOError subclass: #SQLite3IOErrorUnlock
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
SQLite3IOErrorUnlock guid: (GUID fromString: '{5aedccf9-621a-4838-980d-d0eb7ec5fc74}')!
SQLite3IOErrorUnlock comment: 'SQLite3IOErrorUnlock class	instanceVariableNames: '''''!
!SQLite3IOErrorUnlock categoriesForClass!SQLite3-Core-Errors-Extended! !
!SQLite3IOErrorUnlock class methodsFor!

nativeErrorCode 	^ SQLITE_IOERR_UNLOCK! !
!SQLite3IOErrorUnlock class categoriesForMethods!
nativeErrorCode!private / accessing!public! !
!

