"Filed out from Dolphin Smallalk"!

SQLite3IOError subclass: #SQLite3IOErrorRead
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
SQLite3IOErrorRead guid: (GUID fromString: '{2bf173e6-3051-4742-8c79-25b7e904e958}')!
SQLite3IOErrorRead comment: 'SQLite3IOErrorRead class	instanceVariableNames: '''''!
!SQLite3IOErrorRead categoriesForClass!SQLite3-Core-Errors-Extended! !
!SQLite3IOErrorRead class methodsFor!

nativeErrorCode 	^ SQLITE_IOERR_READ! !
!SQLite3IOErrorRead class categoriesForMethods!
nativeErrorCode!private / accessing!public! !
!

