"Filed out from Dolphin Smallalk"!

SQLite3NativeError subclass: #SQLite3TooBig
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
SQLite3TooBig guid: (GUID fromString: '{27f56b8e-1829-4bf2-9f16-3961d35cd833}')!
SQLite3TooBig comment: 'SQLite3TooBig class	instanceVariableNames: '''''!
!SQLite3TooBig categoriesForClass!SQLite3-Core-Errors! !
!SQLite3TooBig class methodsFor!

nativeErrorCode	^ SQLITE_TOOBIG! !
!SQLite3TooBig class categoriesForMethods!
nativeErrorCode!private / accessing!public! !
!

