"Filed out from Dolphin Smallalk"!

SQLite3NativeError subclass: #SQLite3NotADatabase
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
SQLite3NotADatabase guid: (GUID fromString: '{d2813e81-7f44-44b9-8409-a686f90b4649}')!
SQLite3NotADatabase comment: 'SQLite3NotADatabase class	instanceVariableNames: '''''!
!SQLite3NotADatabase categoriesForClass!SQLite3-Core-Errors! !
!SQLite3NotADatabase class methodsFor!

nativeErrorCode	^ SQLITE_NOTADB! !
!SQLite3NotADatabase class categoriesForMethods!
nativeErrorCode!private / accessing!public! !
!

