"Filed out from Dolphin Smallalk"!

SQLite3IOError subclass: #SQLite3IOErrorGetTempPath
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
SQLite3IOErrorGetTempPath guid: (GUID fromString: '{c4baa53c-9f7c-4762-bc4e-a6eddc9200de}')!
SQLite3IOErrorGetTempPath comment: 'SQLite3IOErrorGetTempPath class	instanceVariableNames: '''''!
!SQLite3IOErrorGetTempPath categoriesForClass!SQLite3-Core-Errors-Extended! !
!SQLite3IOErrorGetTempPath class methodsFor!

nativeErrorCode	^ SQLITE_IOERR_GETTEMPPATH! !
!SQLite3IOErrorGetTempPath class categoriesForMethods!
nativeErrorCode!private / accessing!public! !
!

