"Filed out from Dolphin Smallalk"!

SQLite3NativeError subclass: #SQLite3Corrupt
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
SQLite3Corrupt guid: (GUID fromString: '{737cbf08-bd12-4771-a831-0a5c502ffd00}')!
SQLite3Corrupt comment: 'SQLite3Corrupt class	instanceVariableNames: '''''!
!SQLite3Corrupt categoriesForClass!SQLite3-Core-Errors! !
!SQLite3Corrupt class methodsFor!

nativeErrorCode	^ SQLITE_CORRUPT! !
!SQLite3Corrupt class categoriesForMethods!
nativeErrorCode!private / accessing!public! !
!

