"Filed out from Dolphin Smallalk"!

SQLite3NativeError subclass: #SQLite3SchemaChanged
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
SQLite3SchemaChanged guid: (GUID fromString: '{8b793f02-c0a0-44bc-bdd7-1c0ee45d76d1}')!
SQLite3SchemaChanged comment: 'SQLite3SchemaChanged class	instanceVariableNames: '''''!
!SQLite3SchemaChanged categoriesForClass!SQLite3-Core-Errors! !
!SQLite3SchemaChanged class methodsFor!

nativeErrorCode	^ SQLITE_SCHEMA! !
!SQLite3SchemaChanged class categoriesForMethods!
nativeErrorCode!private / accessing!public! !
!

