"Filed out from Dolphin Smallalk"!

SQLite3IOError subclass: #SQLite3IOErrorShortRead
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
SQLite3IOErrorShortRead guid: (GUID fromString: '{56fbdc5b-f577-4a5e-8a7c-360945f3b0bc}')!
SQLite3IOErrorShortRead comment: 'SQLite3IOErrorShortRead class	instanceVariableNames: '''''!
!SQLite3IOErrorShortRead categoriesForClass!SQLite3-Core-Errors-Extended! !
!SQLite3IOErrorShortRead class methodsFor!

nativeErrorCode 	^ SQLITE_IOERR_SHORT_READ! !
!SQLite3IOErrorShortRead class categoriesForMethods!
nativeErrorCode!private / accessing!public! !
!

