"Filed out from Dolphin Smallalk"!

SQLite3NativeError subclass: #SQLite3Interrupt
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
SQLite3Interrupt guid: (GUID fromString: '{d9d23fe1-d199-4246-a3b7-4504d5452b3a}')!
SQLite3Interrupt comment: 'SQLite3Interrupt class	instanceVariableNames: '''''!
!SQLite3Interrupt categoriesForClass!SQLite3-Core-Errors! !
!SQLite3Interrupt class methodsFor!

nativeErrorCode	^ SQLITE_INTERRUPT! !
!SQLite3Interrupt class categoriesForMethods!
nativeErrorCode!private / accessing!public! !
!

