"Filed out from Dolphin Smallalk"!

SQLite3NativeError subclass: #SQLite3Protocol
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
SQLite3Protocol guid: (GUID fromString: '{16348761-92b9-46bf-8161-1e1dd7cddf49}')!
SQLite3Protocol comment: 'SQLite3Protocol class	instanceVariableNames: '''''!
!SQLite3Protocol categoriesForClass!SQLite3-Core-Errors! !
!SQLite3Protocol class methodsFor!

nativeErrorCode	^ SQLITE_PROTOCOL! !
!SQLite3Protocol class categoriesForMethods!
nativeErrorCode!private / accessing!public! !
!

