"Filed out from Dolphin Smallalk"!

SQLite3CantOpen subclass: #SQLite3CantOpenIsDir
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
SQLite3CantOpenIsDir guid: (GUID fromString: '{212eeda9-0775-46e4-94e3-104df55384ad}')!
SQLite3CantOpenIsDir comment: 'SQLite3CantOpenIsDir class	instanceVariableNames: '''''!
!SQLite3CantOpenIsDir categoriesForClass!SQLite3-Core-Errors-Extended! !
!SQLite3CantOpenIsDir class methodsFor!

nativeErrorCode	^ SQLITE_CANTOPEN_ISDIR! !
!SQLite3CantOpenIsDir class categoriesForMethods!
nativeErrorCode!private / accessing!public! !
!

