"Filed out from Dolphin Smallalk"!

SQLite3NativeError subclass: #SQLite3NoMemory
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
SQLite3NoMemory guid: (GUID fromString: '{3af2fe07-0938-4e91-92cf-325ced8b8da5}')!
SQLite3NoMemory comment: 'SQLite3NoMemory class	instanceVariableNames: '''''!
!SQLite3NoMemory categoriesForClass!SQLite3-Core-Errors! !
!SQLite3NoMemory class methodsFor!

nativeErrorCode	^SQLITE_NOMEM! !
!SQLite3NoMemory class categoriesForMethods!
nativeErrorCode!private / accessing!public! !
!

