"Filed out from Dolphin Smallalk"!

SQLite3IOError subclass: #SQLite3IOErrorSeek
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
SQLite3IOErrorSeek guid: (GUID fromString: '{dbc831a5-dd85-49c7-af36-0c08c1c5ce34}')!
SQLite3IOErrorSeek comment: 'SQLite3IOErrorSeek class	instanceVariableNames: '''''!
!SQLite3IOErrorSeek categoriesForClass!SQLite3-Core-Errors-Extended! !
!SQLite3IOErrorSeek class methodsFor!

nativeErrorCode 	^ SQLITE_IOERR_SEEK! !
!SQLite3IOErrorSeek class categoriesForMethods!
nativeErrorCode!private / accessing!public! !
!

