"Filed out from Dolphin Smallalk"!

SQLite3NativeError subclass: #SQLite3Busy
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
SQLite3Busy guid: (GUID fromString: '{917ee764-467f-475e-bb96-880572edf485}')!
SQLite3Busy comment: 'SQLite3Busy class	instanceVariableNames: '''''!
!SQLite3Busy categoriesForClass!SQLite3-Core-Errors! !
!SQLite3Busy class methodsFor!

nativeErrorCode 		^ SQLITE_BUSY! !
!SQLite3Busy class categoriesForMethods!
nativeErrorCode!private / accessing!public! !
!

