"Filed out from Dolphin Smallalk"!

SQLite3Result subclass: #SQLite3RowResult
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
SQLite3RowResult guid: (GUID fromString: '{fea86c51-90aa-46a4-bf87-c1db9798c8df}')!
SQLite3RowResult comment: 'SQLite3RowResult class	instanceVariableNames: '''''!
!SQLite3RowResult categoriesForClass!SQLite3-Core-Results! !
!SQLite3RowResult class methodsFor!

nativeResultCode	^ SQLITE_ROW! !
!SQLite3RowResult class categoriesForMethods!
nativeResultCode!private / accessing!public! !
!

