"Filed out from Dolphin Smallalk"!

SQLite3NativeError subclass: #SQLite3NotFound
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
SQLite3NotFound guid: (GUID fromString: '{2871d33a-dd63-4a7a-bfaa-80be67c02bc6}')!
SQLite3NotFound comment: 'SQLite3NotFound class	instanceVariableNames: '''''!
!SQLite3NotFound categoriesForClass!SQLite3-Core-Errors! !
!SQLite3NotFound class methodsFor!

nativeErrorCode	^ SQLITE_NOTFOUND! !
!SQLite3NotFound class categoriesForMethods!
nativeErrorCode!private / accessing!public! !
!

