"Filed out from Dolphin Smallalk"!

SQLite3NativeError subclass: #SQLite3Misuse
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
SQLite3Misuse guid: (GUID fromString: '{1cccb0b3-5fd7-42a6-b318-1653c498ea44}')!
SQLite3Misuse comment: 'SQLite3Misuse class	instanceVariableNames: '''''!
!SQLite3Misuse categoriesForClass!SQLite3-Core-Errors! !
!SQLite3Misuse class methodsFor!

nativeErrorCode 		^ SQLITE_MISUSE! !
!SQLite3Misuse class categoriesForMethods!
nativeErrorCode!private / accessing!public! !
!

