"Filed out from Dolphin Smallalk"!

SQLite3ConstraintViolation subclass: #SQLite3ConstraintViolationPrimaryKey
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
SQLite3ConstraintViolationPrimaryKey guid: (GUID fromString: '{17c51761-dc1e-49a6-a2d0-a66bf695d1d9}')!
SQLite3ConstraintViolationPrimaryKey comment: 'SQLite3ConstraintViolationPrimaryKey class	instanceVariableNames: '''''!
!SQLite3ConstraintViolationPrimaryKey categoriesForClass!SQLite3-Core-Errors-Extended! !
!SQLite3ConstraintViolationPrimaryKey class methodsFor!

nativeErrorCode	^ SQLITE_CONSTRAINT_PRIMARYKEY! !
!SQLite3ConstraintViolationPrimaryKey class categoriesForMethods!
nativeErrorCode!private / accessing!public! !
!

