"Filed out from Dolphin Smallalk"!

SQLite3IOError subclass: #SQLite3IOErrorAccess
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
SQLite3IOErrorAccess guid: (GUID fromString: '{fad2920e-fe7e-44ae-9b4b-8817a1780082}')!
SQLite3IOErrorAccess comment: 'SQLite3IOErrorAccess class	instanceVariableNames: '''''!
!SQLite3IOErrorAccess categoriesForClass!SQLite3-Core-Errors-Extended! !
!SQLite3IOErrorAccess class methodsFor!

nativeErrorCode 	^ SQLITE_IOERR_ACCESS! !
!SQLite3IOErrorAccess class categoriesForMethods!
nativeErrorCode!private / accessing!public! !
!

