"Filed out from Dolphin Smallalk"!

SQLite3ReadOnly subclass: #SQLite3ReadOnlyDBMoved
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
SQLite3ReadOnlyDBMoved guid: (GUID fromString: '{39a9af75-6905-4e18-841e-2ab81e483438}')!
SQLite3ReadOnlyDBMoved comment: 'SQLite3ReadOnlyDBMoved class	instanceVariableNames: '''''!
!SQLite3ReadOnlyDBMoved categoriesForClass!SQLite3-Core-Errors-Extended! !
!SQLite3ReadOnlyDBMoved class methodsFor!

nativeErrorCode	^ SQLITE_READONLY_DBMOVED! !
!SQLite3ReadOnlyDBMoved class categoriesForMethods!
nativeErrorCode!private / accessing!public! !
!

