"Filed out from Dolphin Smallalk"!

SQLite3CantOpen subclass: #SQLite3CantOpenNoTempDir
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
SQLite3CantOpenNoTempDir guid: (GUID fromString: '{95270dfd-c67e-4cd7-b68e-ca8879b0615a}')!
SQLite3CantOpenNoTempDir comment: 'SQLite3CantOpenNoTempDir class	instanceVariableNames: '''''!
!SQLite3CantOpenNoTempDir categoriesForClass!SQLite3-Core-Errors-Extended! !
!SQLite3CantOpenNoTempDir class methodsFor!

nativeErrorCode	^ SQLITE_CANTOPEN_NOTEMPDIR! !
!SQLite3CantOpenNoTempDir class categoriesForMethods!
nativeErrorCode!private / accessing!public! !
!

