"Filed out from Dolphin Smallalk"!

SQLite3NativeError subclass: #SQLite3ReadOnly
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
SQLite3ReadOnly guid: (GUID fromString: '{10f3d6a3-0402-4b8a-9be3-0f510eabab3a}')!
SQLite3ReadOnly comment: 'SQLite3ReadOnly class	instanceVariableNames: '''''!
!SQLite3ReadOnly categoriesForClass!SQLite3-Core-Errors! !
!SQLite3ReadOnly class methodsFor!

nativeErrorCode	^ SQLITE_READONLY! !
!SQLite3ReadOnly class categoriesForMethods!
nativeErrorCode!private / accessing!public! !
!

