"Filed out from Dolphin Smallalk"!

SQLite3NativeError subclass: #SQLite3Empty
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
SQLite3Empty guid: (GUID fromString: '{67f3862a-d657-49f2-b5c4-2615d6358cb7}')!
SQLite3Empty comment: 'SQLite3Empty class	instanceVariableNames: '''''!
!SQLite3Empty categoriesForClass!SQLite3-Core-Errors! !
!SQLite3Empty class methodsFor!

nativeErrorCode	^ SQLITE_EMPTY! !
!SQLite3Empty class categoriesForMethods!
nativeErrorCode!private / accessing!public! !
!

