"Filed out from Dolphin Smallalk"!

SQLite3IOError subclass: #SQLite3IOErrorDirClose
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
SQLite3IOErrorDirClose guid: (GUID fromString: '{8da62653-88cb-44b7-b275-92ca50e084d6}')!
SQLite3IOErrorDirClose comment: 'SQLite3IOErrorDirClose class	instanceVariableNames: '''''!
!SQLite3IOErrorDirClose categoriesForClass!SQLite3-Core-Errors-Extended! !
!SQLite3IOErrorDirClose class methodsFor!

nativeErrorCode	^ SQLITE_IOERR_DIR_CLOSE! !
!SQLite3IOErrorDirClose class categoriesForMethods!
nativeErrorCode!private / accessing!public! !
!

