"Filed out from Dolphin Smallalk"!

SQLite3IOErrorSharedMemoryError subclass: #SQLite3IOErrorSharedMemorySize
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
SQLite3IOErrorSharedMemorySize guid: (GUID fromString: '{b8f7105e-a0d4-41bc-a6e9-0634c11746ad}')!
SQLite3IOErrorSharedMemorySize comment: 'SQLite3IOErrorSharedMemorySize class	instanceVariableNames: '''''!
!SQLite3IOErrorSharedMemorySize categoriesForClass!SQLite3-Core-Errors-Extended! !
!SQLite3IOErrorSharedMemorySize class methodsFor!

nativeErrorCode 	^ SQLITE_IOERR_SHMSIZE! !
!SQLite3IOErrorSharedMemorySize class categoriesForMethods!
nativeErrorCode!private / accessing!public! !
!

