"Filed out from Dolphin Smallalk"!

SQLite3NativeError subclass: #SQLite3NoLargeFileSupport
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
SQLite3NoLargeFileSupport guid: (GUID fromString: '{ce650dcb-2bf0-4281-a8d1-9e3305e01311}')!
SQLite3NoLargeFileSupport comment: 'SQLite3NoLargeFileSupport class	instanceVariableNames: '''''!
!SQLite3NoLargeFileSupport categoriesForClass!SQLite3-Core-Errors! !
!SQLite3NoLargeFileSupport class methodsFor!

nativeErrorCode	^ SQLITE_NOLFS! !
!SQLite3NoLargeFileSupport class categoriesForMethods!
nativeErrorCode!private / accessing!public! !
!

