"Filed out from Dolphin Smallalk"!

SQLite3IOError subclass: #SQLite3IOErrorLock
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
SQLite3IOErrorLock guid: (GUID fromString: '{f63d1365-eb5a-4b97-9004-eb130e36edfa}')!
SQLite3IOErrorLock comment: 'SQLite3IOErrorLock class	instanceVariableNames: '''''!
!SQLite3IOErrorLock categoriesForClass!SQLite3-Core-Errors-Extended! !
!SQLite3IOErrorLock class methodsFor!

nativeErrorCode 	^ SQLITE_IOERR_LOCK! !
!SQLite3IOErrorLock class categoriesForMethods!
nativeErrorCode!private / accessing!public! !
!

