"Filed out from Dolphin Smallalk"!

SQLite3ConstraintViolation subclass: #SQLite3ConstraintViolationFunction
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
SQLite3ConstraintViolationFunction guid: (GUID fromString: '{70895f5f-f881-4413-ad8a-b3a6557b9c20}')!
SQLite3ConstraintViolationFunction comment: 'SQLite3ConstraintViolationFunction class	instanceVariableNames: '''''!
!SQLite3ConstraintViolationFunction categoriesForClass!SQLite3-Core-Errors-Extended! !
!SQLite3ConstraintViolationFunction class methodsFor!

nativeErrorCode	^ SQLITE_CONSTRAINT_FUNCTION! !
!SQLite3ConstraintViolationFunction class categoriesForMethods!
nativeErrorCode!private / accessing!public! !
!

