"Filed out from Dolphin Smallalk"!

SQLite3NativeError subclass: #SQLite3LogWarning
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
SQLite3LogWarning guid: (GUID fromString: '{dc0b88de-0e7b-4101-b7a3-3ebf83bf4451}')!
SQLite3LogWarning comment: 'SQLite3LogWarning class	instanceVariableNames: '''''!
!SQLite3LogWarning categoriesForClass!SQLite3-Core-Errors! !
!SQLite3LogWarning class methodsFor!

nativeErrorCode	^ SQLITE_WARNING! !
!SQLite3LogWarning class categoriesForMethods!
nativeErrorCode!private / accessing!public! !
!

