"Filed out from Dolphin Smallalk"!

SQLite3IOError subclass: #SQLite3IOErrorTruncate
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
SQLite3IOErrorTruncate guid: (GUID fromString: '{276c3d3a-d94f-416b-8256-9c53a4ca46b5}')!
SQLite3IOErrorTruncate comment: 'SQLite3IOErrorTruncate class	instanceVariableNames: '''''!
!SQLite3IOErrorTruncate categoriesForClass!SQLite3-Core-Errors-Extended! !
!SQLite3IOErrorTruncate class methodsFor!

nativeErrorCode	^ SQLITE_IOERR_TRUNCATE! !
!SQLite3IOErrorTruncate class categoriesForMethods!
nativeErrorCode!private / accessing!public! !
!

