"Filed out from Dolphin Smallalk"!

SQLite3ConstraintViolation subclass: #SQLite3ConstraintViolationVirtualTable
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
SQLite3ConstraintViolationVirtualTable guid: (GUID fromString: '{32b9b8ac-bcc5-43a1-83ab-477a6f7100e1}')!
SQLite3ConstraintViolationVirtualTable comment: 'SQLite3ConstraintViolationVirtualTable class	instanceVariableNames: '''''!
!SQLite3ConstraintViolationVirtualTable categoriesForClass!SQLite3-Core-Errors-Extended! !
!SQLite3ConstraintViolationVirtualTable class methodsFor!

nativeErrorCode 	^ SQLITE_CONSTRAINT_VTAB! !
!SQLite3ConstraintViolationVirtualTable class categoriesForMethods!
nativeErrorCode!private / accessing!public! !
!

