"Filed out from Dolphin Smallalk"!

SQLite3IOErrorSharedMemoryError subclass: #SQLite3IOErrorSharedMemoryLock
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
SQLite3IOErrorSharedMemoryLock guid: (GUID fromString: '{26cc1376-21fa-4063-90bf-d91c3132b8e3}')!
SQLite3IOErrorSharedMemoryLock comment: 'SQLite3IOErrorSharedMemoryLock class	instanceVariableNames: '''''!
!SQLite3IOErrorSharedMemoryLock categoriesForClass!SQLite3-Core-Errors-Extended! !
!SQLite3IOErrorSharedMemoryLock class methodsFor!

nativeErrorCode	^ SQLITE_IOERR_SHMLOCK! !
!SQLite3IOErrorSharedMemoryLock class categoriesForMethods!
nativeErrorCode!private / accessing!public! !
!

