"Filed out from Dolphin Smallalk"!

SQLite3NativeError subclass: #SQLite3Internal
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
SQLite3Internal guid: (GUID fromString: '{4639aa18-4768-4065-adf3-a8778cc2ffdf}')!
SQLite3Internal comment: 'SQLite3Internal class	instanceVariableNames: '''''!
!SQLite3Internal categoriesForClass!SQLite3-Core-Errors! !
!SQLite3Internal class methodsFor!

nativeErrorCode		^ SQLITE_INTERNAL! !
!SQLite3Internal class categoriesForMethods!
nativeErrorCode!private / accessing!public! !
!

