"Filed out from Dolphin Smallalk"!

SQLite3IOError subclass: #SQLite3IOErrorDirFSync
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
SQLite3IOErrorDirFSync guid: (GUID fromString: '{efc0d241-5912-41c3-bd28-dc024509ebc2}')!
SQLite3IOErrorDirFSync comment: 'SQLite3IOErrorDirFSync class	instanceVariableNames: '''''!
!SQLite3IOErrorDirFSync categoriesForClass!SQLite3-Core-Errors-Extended! !
!SQLite3IOErrorDirFSync class methodsFor!

nativeErrorCode 	^ SQLITE_IOERR_DIR_FSYNC! !
!SQLite3IOErrorDirFSync class categoriesForMethods!
nativeErrorCode!private / accessing!public! !
!

