"Filed out from Dolphin Smallalk"!

SQLite3NativeError subclass: #SQLite3Mismatch
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
SQLite3Mismatch guid: (GUID fromString: '{b6df1bab-7189-4986-a571-0329da8241be}')!
SQLite3Mismatch comment: 'SQLite3Mismatch class	instanceVariableNames: '''''!
!SQLite3Mismatch categoriesForClass!SQLite3-Core-Errors! !
!SQLite3Mismatch class methodsFor!

nativeErrorCode	^ SQLITE_MISMATCH! !
!SQLite3Mismatch class categoriesForMethods!
nativeErrorCode!private / accessing!public! !
!

