"Filed out from Dolphin Smallalk"!

SQLite3LogNotice subclass: #SQLite3LogNoticeRecoverRollback
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
SQLite3LogNoticeRecoverRollback guid: (GUID fromString: '{ce4e65a2-618e-4e6a-b87b-401c0120372c}')!
SQLite3LogNoticeRecoverRollback comment: 'SQLite3LogNoticeRecoverRollback class	instanceVariableNames: '''''!
!SQLite3LogNoticeRecoverRollback categoriesForClass!SQLite3-Core-Errors-Extended! !
!SQLite3LogNoticeRecoverRollback class methodsFor!

nativeErrorCode	^ SQLITE_NOTICE_RECOVER_ROLLBACK! !
!SQLite3LogNoticeRecoverRollback class categoriesForMethods!
nativeErrorCode!private / accessing!public! !
!

