"Filed out from Dolphin Smallalk"!

SQLite3ReadOnly subclass: #SQLite3ReadOnlyCantLock
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
SQLite3ReadOnlyCantLock guid: (GUID fromString: '{48141edc-b2f0-4d4c-884b-478ca5a04032}')!
SQLite3ReadOnlyCantLock comment: 'SQLite3ReadOnlyCantLock class	instanceVariableNames: '''''!
!SQLite3ReadOnlyCantLock categoriesForClass!SQLite3-Core-Errors-Extended! !
!SQLite3ReadOnlyCantLock class methodsFor!

nativeErrorCode	^ SQLITE_READONLY_CANTLOCK! !
!SQLite3ReadOnlyCantLock class categoriesForMethods!
nativeErrorCode!private / accessing!public! !
!

