"Filed out from Dolphin Smallalk"!

SQLite3NativeError subclass: #SQLite3Format
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
SQLite3Format guid: (GUID fromString: '{98bf007e-7eb4-4672-b5ba-a304bcfb84bb}')!
SQLite3Format comment: 'SQLite3Format class	instanceVariableNames: '''''!
!SQLite3Format categoriesForClass!SQLite3-Core-Errors! !
!SQLite3Format class methodsFor!

nativeErrorCode	^ SQLITE_FORMAT! !
!SQLite3Format class categoriesForMethods!
nativeErrorCode!private / accessing!public! !
!

