"Filed out from Dolphin Smallalk"!

SQLite3ConstraintViolation subclass: #SQLite3ConstraintViolationCheck
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
SQLite3ConstraintViolationCheck guid: (GUID fromString: '{f58e4536-aabe-48b8-a987-369fef4b5079}')!
SQLite3ConstraintViolationCheck comment: 'SQLite3ConstraintViolationCheck class	instanceVariableNames: '''''!
!SQLite3ConstraintViolationCheck categoriesForClass!SQLite3-Core-Errors-Extended! !
!SQLite3ConstraintViolationCheck class methodsFor!

nativeErrorCode	^ SQLITE_CONSTRAINT_CHECK! !
!SQLite3ConstraintViolationCheck class categoriesForMethods!
nativeErrorCode!private / accessing!public! !
!

