"Filed out from Dolphin Smallalk"!

AnsiString variableByteSubclass: #SQLite3DateTimeString
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
SQLite3DateTimeString guid: (GUID fromString: '{3234dab3-78c8-40f6-a95f-21ceff8df64f}')!
SQLite3DateTimeString isNullTerminated: true!
SQLite3DateTimeString comment: 'Object subclass: #SQLite3Backup	instanceVariableNames: ''library srcConnection srcName dstConnection dstName isOpen handle''	classVariableNames: ''''	package: ''SQLite3-Core-Connections'''!
!SQLite3DateTimeString categoriesForClass!SQLite3-Core-Types! !
