"Filed out from Dolphin Smallalk"!

SQLite3NativeError subclass: #SQLite3OutOfRange
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
SQLite3OutOfRange guid: (GUID fromString: '{5c53e5ab-482d-4045-9f84-390101a75b5d}')!
SQLite3OutOfRange comment: 'SQLite3OutOfRange class	instanceVariableNames: '''''!
!SQLite3OutOfRange categoriesForClass!SQLite3-Core-Errors! !
!SQLite3OutOfRange class methodsFor!

nativeErrorCode	^ SQLITE_RANGE! !
!SQLite3OutOfRange class categoriesForMethods!
nativeErrorCode!private / accessing!public! !
!

