"Filed out from Dolphin Smallalk"!

SQLite3NativeError subclass: #SQLite3Locked
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
SQLite3Locked guid: (GUID fromString: '{28a2efc6-ad87-4b22-be6c-3843e40c76f2}')!
SQLite3Locked comment: 'SQLite3Locked class	instanceVariableNames: '''''!
!SQLite3Locked categoriesForClass!SQLite3-Core-Errors! !
!SQLite3Locked class methodsFor!

nativeErrorCode 		^ SQLITE_LOCKED! !
!SQLite3Locked class categoriesForMethods!
nativeErrorCode!private / accessing!public! !
!

