"Filed out from Dolphin Smallalk"!

SQLite3ConstraintViolation subclass: #SQLite3ConstraintViolationRowID
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
SQLite3ConstraintViolationRowID guid: (GUID fromString: '{f5af0d3a-c9a4-402d-8a6a-4d9c99f8f380}')!
SQLite3ConstraintViolationRowID comment: 'SQLite3ConstraintViolationRowID class	instanceVariableNames: '''''!
!SQLite3ConstraintViolationRowID categoriesForClass!SQLite3-Core-Errors-Extended! !
!SQLite3ConstraintViolationRowID class methodsFor!

nativeErrorCode	^ SQLITE_CONSTRAINT_ROWID! !
!SQLite3ConstraintViolationRowID class categoriesForMethods!
nativeErrorCode!private / accessing!public! !
!

