"Filed out from Dolphin Smallalk"!

SQLite3ConstraintViolation subclass: #SQLite3ConstraintViolationForeignKey
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
SQLite3ConstraintViolationForeignKey guid: (GUID fromString: '{7e755127-b88b-405e-9ec4-0c21cd367a15}')!
SQLite3ConstraintViolationForeignKey comment: 'SQLite3ConstraintViolationForeignKey class	instanceVariableNames: '''''!
!SQLite3ConstraintViolationForeignKey categoriesForClass!SQLite3-Core-Errors-Extended! !
!SQLite3ConstraintViolationForeignKey class methodsFor!

nativeErrorCode	^ SQLITE_CONSTRAINT_FOREIGNKEY! !
!SQLite3ConstraintViolationForeignKey class categoriesForMethods!
nativeErrorCode!private / accessing!public! !
!

