"Filed out from Dolphin Smallalk"!

SQLite3Locked subclass: #SQLite3LockedSharedCache
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
SQLite3LockedSharedCache guid: (GUID fromString: '{70c3fdee-88c6-4159-9dbc-74c25e999e12}')!
SQLite3LockedSharedCache comment: 'SQLite3LockedSharedCache class	instanceVariableNames: '''''!
!SQLite3LockedSharedCache categoriesForClass!SQLite3-Core-Errors-Extended! !
!SQLite3LockedSharedCache class methodsFor!

nativeErrorCode	^ SQLITE_LOCKED_SHAREDCACHE! !
!SQLite3LockedSharedCache class categoriesForMethods!
nativeErrorCode!private / accessing!public! !
!

