"Filed out from Dolphin Smallalk"!

SQLite3LogNotice subclass: #SQLite3LogNoticeRecoverWriteAheadLogging
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
SQLite3LogNoticeRecoverWriteAheadLogging guid: (GUID fromString: '{bba330c9-31d7-4226-8882-ec9a6661eb80}')!
SQLite3LogNoticeRecoverWriteAheadLogging comment: 'SQLite3LogNoticeRecoverWriteAheadLogging class	instanceVariableNames: '''''!
!SQLite3LogNoticeRecoverWriteAheadLogging categoriesForClass!SQLite3-Core-Errors-Extended! !
!SQLite3LogNoticeRecoverWriteAheadLogging class methodsFor!

nativeErrorCode	^ SQLITE_NOTICE_RECOVER_WAL! !
!SQLite3LogNoticeRecoverWriteAheadLogging class categoriesForMethods!
nativeErrorCode!private / accessing!public! !
!

