"Filed out from Dolphin Smallalk"!

SQLite3CantOpen subclass: #SQLite3CantOpenConvertPath
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
SQLite3CantOpenConvertPath guid: (GUID fromString: '{0a7e3381-3c4d-4d63-a2a1-112a4a65fbb9}')!
SQLite3CantOpenConvertPath comment: 'SQLite3CantOpenConvertPath class	instanceVariableNames: '''''!
!SQLite3CantOpenConvertPath categoriesForClass!SQLite3-Core-Errors-Extended! !
!SQLite3CantOpenConvertPath class methodsFor!

nativeErrorCode	^ SQLITE_CANTOPEN_CONVPATH! !
!SQLite3CantOpenConvertPath class categoriesForMethods!
nativeErrorCode!private / accessing!public! !
!

