"Filed out from Dolphin Smallalk"!

SQLite3IOError subclass: #SQLite3IOErrorClose
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
SQLite3IOErrorClose guid: (GUID fromString: '{6c9e3984-99d2-4ff4-9d98-8c40cce4f0bf}')!
SQLite3IOErrorClose comment: 'SQLite3IOErrorClose class	instanceVariableNames: '''''!
!SQLite3IOErrorClose categoriesForClass!SQLite3-Core-Errors-Extended! !
!SQLite3IOErrorClose class methodsFor!

nativeErrorCode 	^ SQLITE_IOERR_CLOSE! !
!SQLite3IOErrorClose class categoriesForMethods!
nativeErrorCode!private / accessing!public! !
!

