"Filed out from Dolphin Smallalk"!

SQLite3IOError subclass: #SQLite3IOErrorNoMemory
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
SQLite3IOErrorNoMemory guid: (GUID fromString: '{d56a98c4-a25b-4860-a2b6-52d4c1e34189}')!
SQLite3IOErrorNoMemory comment: 'SQLite3IOErrorNoMemory class	instanceVariableNames: '''''!
!SQLite3IOErrorNoMemory categoriesForClass!SQLite3-Core-Errors-Extended! !
!SQLite3IOErrorNoMemory class methodsFor!

nativeErrorCode 	^ SQLITE_IOERR_NOMEM! !
!SQLite3IOErrorNoMemory class categoriesForMethods!
nativeErrorCode!private / accessing!public! !
!

