"Filed out from Dolphin Smallalk"!

SQLite3NativeError subclass: #SQLite3AuthorizationDenied
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
SQLite3AuthorizationDenied guid: (GUID fromString: '{e296cec3-b411-4ac0-958c-91d063cae7fe}')!
SQLite3AuthorizationDenied comment: 'SQLite3AuthorizationDenied class	instanceVariableNames: '''''!
!SQLite3AuthorizationDenied categoriesForClass!SQLite3-Core-Errors! !
!SQLite3AuthorizationDenied class methodsFor!

nativeErrorCode		^ SQLITE_AUTH! !
!SQLite3AuthorizationDenied class categoriesForMethods!
nativeErrorCode!private / accessing!public! !
!

