"Filed out from Dolphin Smallalk"!

SQLite3IOError subclass: #SQLite3IOErrorWrite
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
SQLite3IOErrorWrite guid: (GUID fromString: '{573de6e9-1d44-468a-8bc0-8dc6a073a051}')!
SQLite3IOErrorWrite comment: 'SQLite3IOErrorWrite class	instanceVariableNames: '''''!
!SQLite3IOErrorWrite categoriesForClass!SQLite3-Core-Errors-Extended! !
!SQLite3IOErrorWrite class methodsFor!

nativeErrorCode 	^ SQLITE_IOERR_WRITE! !
!SQLite3IOErrorWrite class categoriesForMethods!
nativeErrorCode!private / accessing!public! !
!

