"Filed out from Dolphin Smallalk"!

SQLite3NativeError subclass: #SQLite3CantOpen
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
SQLite3CantOpen guid: (GUID fromString: '{3172fd69-62ed-4444-9607-614814a89026}')!
SQLite3CantOpen comment: 'SQLite3CantOpen class	instanceVariableNames: '''''!
!SQLite3CantOpen categoriesForClass!SQLite3-Core-Errors! !
!SQLite3CantOpen class methodsFor!

nativeErrorCode	^ SQLITE_CANTOPEN! !
!SQLite3CantOpen class categoriesForMethods!
nativeErrorCode!private / accessing!public! !
!

