"Filed out from Dolphin Smallalk"!

SQLite3AbstractError subclass: #SQLite3NotOpen
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
SQLite3NotOpen guid: (GUID fromString: '{86f0dce9-f5a0-4570-b603-190dfc7a877f}')!
SQLite3NotOpen comment: 'SQLite3NativeError subclass: #SQLite3OutOfRange	instanceVariableNames: ''''	classVariableNames: ''''	package: ''SQLite3-Core-Errors'''!
!SQLite3NotOpen categoriesForClass!SQLite3-Core-Errors! !
