"Filed out from Dolphin Smallalk"!

SQLite3IOError subclass: #SQLite3IOErrorDelete
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
SQLite3IOErrorDelete guid: (GUID fromString: '{ed8251db-2bb2-4d2c-a0d9-b0730f1e1fc5}')!
SQLite3IOErrorDelete comment: 'SQLite3IOErrorDelete class	instanceVariableNames: '''''!
!SQLite3IOErrorDelete categoriesForClass!SQLite3-Core-Errors-Extended! !
!SQLite3IOErrorDelete class methodsFor!

nativeErrorCode 	^ SQLITE_IOERR_DELETE! !
!SQLite3IOErrorDelete class categoriesForMethods!
nativeErrorCode!private / accessing!public! !
!

