"Filed out from Dolphin Smallalk"!

SQLite3IOError subclass: #SQLite3IOErrorSharedMemoryError
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
SQLite3IOErrorSharedMemoryError guid: (GUID fromString: '{d08241c3-2d6c-4f79-8d85-351a34ef07bc}')!
SQLite3IOErrorSharedMemoryError comment: 'SQLite3IOErrorSharedMemoryError class	instanceVariableNames: '''''!
!SQLite3IOErrorSharedMemoryError categoriesForClass!SQLite3-Core-Errors-Extended! !
!SQLite3IOErrorSharedMemoryError class methodsFor!

isAbstract	^self name = #SQLite3IOErrorSharedMemoryError! !
!SQLite3IOErrorSharedMemoryError class categoriesForMethods!
isAbstract!public!testing! !
!

