"Filed out from Dolphin Smallalk"!

SQLite3NativeError subclass: #SQLite3ConstraintViolation
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
SQLite3ConstraintViolation guid: (GUID fromString: '{e8d0820a-4045-4136-afac-a0035077f900}')!
SQLite3ConstraintViolation comment: 'SQLite3ConstraintViolation class	instanceVariableNames: '''''!
!SQLite3ConstraintViolation categoriesForClass!SQLite3-Core-Errors! !
!SQLite3ConstraintViolation class methodsFor!

nativeErrorCode		^ SQLITE_CONSTRAINT! !
!SQLite3ConstraintViolation class categoriesForMethods!
nativeErrorCode!private / accessing!public! !
!

