"Filed out from Dolphin Smallalk"!

SQLite3ConstraintViolation subclass: #SQLite3ConstraintViolationNotNull
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
SQLite3ConstraintViolationNotNull guid: (GUID fromString: '{fbb21a91-3969-42da-b881-5f928c1da7b7}')!
SQLite3ConstraintViolationNotNull comment: 'SQLite3ConstraintViolationNotNull class	instanceVariableNames: '''''!
!SQLite3ConstraintViolationNotNull categoriesForClass!SQLite3-Core-Errors-Extended! !
!SQLite3ConstraintViolationNotNull class methodsFor!

nativeErrorCode	^ SQLITE_CONSTRAINT_NOTNULL! !
!SQLite3ConstraintViolationNotNull class categoriesForMethods!
nativeErrorCode!private / accessing!public! !
!

