"Filed out from Dolphin Smallalk"!

SQLite3ConstraintViolation subclass: #SQLite3ConstraintViolationCommitHook
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
SQLite3ConstraintViolationCommitHook guid: (GUID fromString: '{ce12517a-34a8-4207-bedd-a3bb9d3dae71}')!
SQLite3ConstraintViolationCommitHook comment: 'SQLite3ConstraintViolationCommitHook class	instanceVariableNames: '''''!
!SQLite3ConstraintViolationCommitHook categoriesForClass!SQLite3-Core-Errors-Extended! !
!SQLite3ConstraintViolationCommitHook class methodsFor!

nativeErrorCode	^ SQLITE_CONSTRAINT_COMMITHOOK! !
!SQLite3ConstraintViolationCommitHook class categoriesForMethods!
nativeErrorCode!private / accessing!public! !
!

