"Filed out from Dolphin Smallalk"!

SQLite3IOError subclass: #SQLite3IOErrorFStat
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
SQLite3IOErrorFStat guid: (GUID fromString: '{9106d2b2-c367-4453-9867-dacbc2f998e7}')!
SQLite3IOErrorFStat comment: 'SQLite3IOErrorFStat class	instanceVariableNames: '''''!
!SQLite3IOErrorFStat categoriesForClass!SQLite3-Core-Errors-Extended! !
!SQLite3IOErrorFStat class methodsFor!

nativeErrorCode	^ SQLITE_IOERR_FSTAT! !
!SQLite3IOErrorFStat class categoriesForMethods!
nativeErrorCode!private / accessing!public! !
!

