"Filed out from Dolphin Smallalk"!

SQLite3Result subclass: #SQLite3DoneResult
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
SQLite3DoneResult guid: (GUID fromString: '{0a741f3d-4e45-4ef0-8f06-482f5661e6f1}')!
SQLite3DoneResult comment: 'SQLite3DoneResult class	instanceVariableNames: '''''!
!SQLite3DoneResult categoriesForClass!SQLite3-Core-Results! !
!SQLite3DoneResult class methodsFor!

nativeResultCode	^ SQLITE_DONE! !
!SQLite3DoneResult class categoriesForMethods!
nativeResultCode!private / accessing!public! !
!

