"Filed out from Dolphin Smallalk"!

SQLite3ReadOnly subclass: #SQLite3ReadOnlyRollback
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
SQLite3ReadOnlyRollback guid: (GUID fromString: '{f46cfc3a-ed90-4fca-a251-280e4fff5e2e}')!
SQLite3ReadOnlyRollback comment: 'SQLite3ReadOnlyRollback class	instanceVariableNames: '''''!
!SQLite3ReadOnlyRollback categoriesForClass!SQLite3-Core-Errors-Extended! !
!SQLite3ReadOnlyRollback class methodsFor!

nativeErrorCode	^ SQLITE_READONLY_ROLLBACK! !
!SQLite3ReadOnlyRollback class categoriesForMethods!
nativeErrorCode!private / accessing!public! !
!

