"Filed out from Dolphin Smallalk"!

SQLite3NativeError subclass: #SQLite3Permission
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
SQLite3Permission guid: (GUID fromString: '{d330dd49-8dc8-4474-b3c3-74ca86a97f4a}')!
SQLite3Permission comment: 'SQLite3Permission class	instanceVariableNames: '''''!
!SQLite3Permission categoriesForClass!SQLite3-Core-Errors! !
!SQLite3Permission class methodsFor!

nativeErrorCode	^ SQLITE_PERM! !
!SQLite3Permission class categoriesForMethods!
nativeErrorCode!private / accessing!public! !
!

