"Filed out from Dolphin Smallalk"!

SQLite3IOError subclass: #SQLite3IOErrorMemoryMap
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
SQLite3IOErrorMemoryMap guid: (GUID fromString: '{0511670b-71cb-4d82-a4a2-4a30f0586b77}')!
SQLite3IOErrorMemoryMap comment: 'SQLite3IOErrorMemoryMap class	instanceVariableNames: '''''!
!SQLite3IOErrorMemoryMap categoriesForClass!SQLite3-Core-Errors-Extended! !
!SQLite3IOErrorMemoryMap class methodsFor!

nativeErrorCode	^ SQLITE_IOERR_MMAP! !
!SQLite3IOErrorMemoryMap class categoriesForMethods!
nativeErrorCode!private / accessing!public! !
!

