"Filed out from Dolphin Smallalk"!

SQLite3IOError subclass: #SQLite3IOErrorReadLock
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
SQLite3IOErrorReadLock guid: (GUID fromString: '{3ebcaf3e-a2fb-44e2-9a5b-3c0fc643b355}')!
SQLite3IOErrorReadLock comment: 'SQLite3IOErrorReadLock class	instanceVariableNames: '''''!
!SQLite3IOErrorReadLock categoriesForClass!SQLite3-Core-Errors-Extended! !
!SQLite3IOErrorReadLock class methodsFor!

nativeErrorCode	^ SQLITE_IOERR_RDLOCK! !
!SQLite3IOErrorReadLock class categoriesForMethods!
nativeErrorCode!private / accessing!public! !
!

