"Filed out from Dolphin Smallalk"!

SQLite3ConstraintViolation subclass: #SQLite3ConstraintViolationUnique
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
SQLite3ConstraintViolationUnique guid: (GUID fromString: '{0b7d47b5-e6c3-4554-b3cb-d0800ee671a8}')!
SQLite3ConstraintViolationUnique comment: 'SQLite3ConstraintViolationUnique class	instanceVariableNames: '''''!
!SQLite3ConstraintViolationUnique categoriesForClass!SQLite3-Core-Errors-Extended! !
!SQLite3ConstraintViolationUnique class methodsFor!

nativeErrorCode 	^ SQLITE_CONSTRAINT_UNIQUE! !
!SQLite3ConstraintViolationUnique class categoriesForMethods!
nativeErrorCode!private / accessing!public! !
!

