"Filed out from Dolphin Smallalk"!

SQLite3IOError subclass: #SQLite3IOErrorBlocked
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
SQLite3IOErrorBlocked guid: (GUID fromString: '{1577baf1-a711-46be-a13b-dca03611baee}')!
SQLite3IOErrorBlocked comment: 'SQLite3IOErrorBlocked class	instanceVariableNames: '''''!
!SQLite3IOErrorBlocked categoriesForClass!SQLite3-Core-Errors-Extended! !
!SQLite3IOErrorBlocked class methodsFor!

nativeErrorCode 	^ SQLITE_IOERR_BLOCKED! !
!SQLite3IOErrorBlocked class categoriesForMethods!
nativeErrorCode!private / accessing!public! !
!

