"Filed out from Dolphin Smallalk"!

SQLite3NativeError subclass: #SQLite3Error
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
SQLite3Error guid: (GUID fromString: '{4d3e1e15-7b21-48e0-a83c-53532bbe2a86}')!
SQLite3Error comment: 'SQLite3Error class	instanceVariableNames: '''''!
!SQLite3Error categoriesForClass!SQLite3-Core-Errors! !
!SQLite3Error class methodsFor!

nativeErrorCode		^ SQLITE_ERROR! !
!SQLite3Error class categoriesForMethods!
nativeErrorCode!private / accessing!public! !
!

