"Filed out from Dolphin Smallalk"!

SQLite3Corrupt subclass: #SQLite3CorruptVirtualTable
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
SQLite3CorruptVirtualTable guid: (GUID fromString: '{2b87aa70-7b1d-4977-a04e-9dc6c88be56d}')!
SQLite3CorruptVirtualTable comment: 'SQLite3CorruptVirtualTable class	instanceVariableNames: '''''!
!SQLite3CorruptVirtualTable categoriesForClass!SQLite3-Core-Errors-Extended! !
!SQLite3CorruptVirtualTable class methodsFor!

nativeErrorCode	^ SQLITE_CORRUPT_VTAB! !
!SQLite3CorruptVirtualTable class categoriesForMethods!
nativeErrorCode!private / accessing!public! !
!

