"Filed out from Dolphin Smallalk"!

SQLite3IOError subclass: #SQLite3IOErrorFSync
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
SQLite3IOErrorFSync guid: (GUID fromString: '{cae3fc7c-bde3-433e-b2e2-3f58997e9e6c}')!
SQLite3IOErrorFSync comment: 'SQLite3IOErrorFSync class	instanceVariableNames: '''''!
!SQLite3IOErrorFSync categoriesForClass!SQLite3-Core-Errors-Extended! !
!SQLite3IOErrorFSync class methodsFor!

nativeErrorCode 	^ SQLITE_IOERR_FSYNC! !
!SQLite3IOErrorFSync class categoriesForMethods!
nativeErrorCode!private / accessing!public! !
!

