"Filed out from Dolphin Smallalk"!

SQLite3CantOpen subclass: #SQLite3CantOpenFullPath
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
SQLite3CantOpenFullPath guid: (GUID fromString: '{256ddcbf-d8bd-44e7-a9c5-bc730c48824a}')!
SQLite3CantOpenFullPath comment: 'SQLite3CantOpenFullPath class	instanceVariableNames: '''''!
!SQLite3CantOpenFullPath categoriesForClass!SQLite3-Core-Errors-Extended! !
!SQLite3CantOpenFullPath class methodsFor!

nativeErrorCode	^ SQLITE_CANTOPEN_FULLPATH! !
!SQLite3CantOpenFullPath class categoriesForMethods!
nativeErrorCode!private / accessing!public! !
!

