"Filed out from Dolphin Smallalk"!

SQLite3NativeError subclass: #SQLite3Full
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
SQLite3Full guid: (GUID fromString: '{7bb2cb6c-cd8f-4cab-af31-c7725933d572}')!
SQLite3Full comment: 'SQLite3Full class	instanceVariableNames: '''''!
!SQLite3Full categoriesForClass!SQLite3-Core-Errors! !
!SQLite3Full class methodsFor!

nativeErrorCode		^ SQLITE_FULL! !
!SQLite3Full class categoriesForMethods!
nativeErrorCode!private / accessing!public! !
!

