"Filed out from Dolphin Smallalk"!

SQLite3IOErrorSharedMemoryError subclass: #SQLite3IOErrorSharedMemoryMap
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
SQLite3IOErrorSharedMemoryMap guid: (GUID fromString: '{0c9b446a-b6b9-4138-88e7-c47536f8e0b0}')!
SQLite3IOErrorSharedMemoryMap comment: 'SQLite3IOErrorSharedMemoryMap class	instanceVariableNames: '''''!
!SQLite3IOErrorSharedMemoryMap categoriesForClass!SQLite3-Core-Errors-Extended! !
!SQLite3IOErrorSharedMemoryMap class methodsFor!

nativeErrorCode	^ SQLITE_IOERR_SHMMAP! !
!SQLite3IOErrorSharedMemoryMap class categoriesForMethods!
nativeErrorCode!private / accessing!public! !
!

