"Filed out from Dolphin Smallalk"!

SQLite3Busy subclass: #SQLite3BusySnapshot
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
SQLite3BusySnapshot guid: (GUID fromString: '{22a33fb6-85f2-45ff-a386-418e5c760b38}')!
SQLite3BusySnapshot comment: 'SQLite3BusySnapshot class	instanceVariableNames: '''''!
!SQLite3BusySnapshot categoriesForClass!SQLite3-Core-Errors-Extended! !
!SQLite3BusySnapshot class methodsFor!

nativeErrorCode	^ SQLITE_BUSY_SNAPSHOT! !
!SQLite3BusySnapshot class categoriesForMethods!
nativeErrorCode!private / accessing!public! !
!

