"Filed out from Dolphin Smallalk"!

SQLite3ConstraintViolation subclass: #SQLite3ConstraintViolationTrigger
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
SQLite3ConstraintViolationTrigger guid: (GUID fromString: '{fe5909fc-5fb9-4490-8b52-54c455ca00c2}')!
SQLite3ConstraintViolationTrigger comment: 'SQLite3ConstraintViolationTrigger class	instanceVariableNames: '''''!
!SQLite3ConstraintViolationTrigger categoriesForClass!SQLite3-Core-Errors-Extended! !
!SQLite3ConstraintViolationTrigger class methodsFor!

nativeErrorCode	^ SQLITE_CONSTRAINT_TRIGGER! !
!SQLite3ConstraintViolationTrigger class categoriesForMethods!
nativeErrorCode!private / accessing!public! !
!

